import './globals.css'
import { Iceberg } from 'next/font/google'
import Nav from './components/nav'

export const metadata = {
  title: 'Welcome To PIAIC',
  description: 'Generated by create next app',
}

const iceberg=Iceberg({
  subsets:['latin'],
  variable:'--font-iceberg',
  display:'swap',
  weight:"400"
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${iceberg.variable} font-iceberg`}>
      <body >
        <Nav/>
        {children}
      </body>
    </html>
  )
}
